server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dplayer
#      username: ""
#      password: ""
      authentication-database: admin
      uri: mongodb://localhost:27017/dplayer

default:
  pageNo: 0
  pageSize: 5
  direction: DESC
  entity: UPDATE_TIME_STAMP

logging:
  level:
    web: debug